version: '3.7'

services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /server/node_modules
      - ./server:/app
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  sample:
    build:
      dockerfile: Dockerfile
      context: "./client"
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true